# elb variables
variable "sg_map" {}
variable "subnets" {}
variable "vpc_id" {}
variable "healthy_threshold" {}
variable "unhealthy_threshold" {}
variable "interval" {}
variable "timeout" {}
variable "private_instances" {}